/** Generated by scripts/generate-settings-schema.mjs — do not edit. */

export interface GeneratedSettingSchema {
  /** Key without the `vscodesync.` prefix. */
  key: string;
  type: string;
  description: string;
  default?: unknown;
  enum?: unknown[];
  enumDescriptions?: string[];
  minimum?: number;
  maximum?: number;
}

export const SETTINGS_SCHEMA: readonly GeneratedSettingSchema[] = [
  {
    "key": "activityRetentionDays",
    "type": "number",
    "description": "Сколько дней хранить записи Activity Feed в ~/.vscode/vscodeSync/activity.json",
    "default": 90,
    "minimum": 1,
    "maximum": 3650
  },
  {
    "key": "ai.pathMapper.enabled",
    "type": "boolean",
    "description": "Разрешить `vscodesync.aiPathMapper` отправлять записи манифеста (только относительные пути, без содержимого) в LM для предложений path-remap. По умолчанию выключено — opt-in.",
    "default": false
  },
  {
    "key": "ai.sessionSummary.enabled",
    "type": "boolean",
    "description": "Разрешить `vscodesync.aiSessionSummary` отправлять локальные activity-события (timestamps + workspace id + относительные пути) в подключённую языковую модель. По умолчанию выключено — opt-in. Provider модели (Copilot, локальный LLM и т.д.) тот же, что для AI merge.",
    "default": false
  },
  {
    "key": "ai.suggestWorkspaceTags.enabled",
    "type": "boolean",
    "description": "Разрешить `vscodesync.aiSuggestWorkspaceTags` отправлять список путей файлов воркспейса в LM для подсказки тегов. По умолчанию выключено — opt-in. Покидают машину только относительные пути; содержимое файлов не отправляется.",
    "default": false
  },
  {
    "key": "aiMerge.enabled",
    "type": "boolean",
    "description": "Включить AI-слияние конфликтов через VS Code Language Model API (Copilot). При активном конфликте в диалоге появляется кнопка «✨ Merge with AI». Требует активного Copilot-подписки.",
    "default": false
  },
  {
    "key": "aiMerge.endpoint",
    "type": "string",
    "description": "AI merge backend. 'vscode-lm' uses the built-in VS Code Language Model API; 'ollama' targets a local Ollama server (http://localhost:11434); 'lm-studio' targets LM Studio's OpenAI-compatible local endpoint (http://localhost:1234). Use a custom http(s):// URL for any other OpenAI-compatible service — non-localhost custom URLs warn before sending content.",
    "default": "vscode-lm"
  },
  {
    "key": "aiMerge.endpointModel",
    "type": "string",
    "description": "Model name passed to the local AI merge endpoint. Ignored when endpoint is 'vscode-lm'.",
    "default": "llama3.2"
  },
  {
    "key": "autoPause.learnedSchedule.enabled",
    "type": "boolean",
    "description": "Auto-pause во время «тихих часов» (v3.M). VSCodeSync кластеризует ваши activity-timestamps за последние 30 дней по hour-of-day и приостанавливает фоновый sync в часы с наименьшей активностью. Ручной sync доступен всегда. По-умолчанию выключено — opt-in.",
    "default": false
  },
  {
    "key": "autoSyncMode",
    "type": "string",
    "description": "**Режим авто-проверки.** `off` — никакой автоматики вовсе; `check-only` (по умолчанию) — авто-триггеры пересчитывают статусы и показывают расхождения (панель, дерево, статус-бар), но **не делают** ни push, ни pull сами. С 1.0.0 расширение двигает файлы только по вашей явной команде — прежний режим `full` удалён.",
    "default": "check-only",
    "enum": [
      "off",
      "check-only"
    ],
    "enumDescriptions": [
      "Отключить любую автоматику. Никаких проверок и обращений к облаку без явной команды пользователя.",
      "Только проверять состояние файлов и подсвечивать расхождения (панель, дерево, статус-бар). Отправка и скачивание — всегда по вашей команде."
    ]
  },
  {
    "key": "backup.intervalDays",
    "type": "number",
    "description": "Интервал cross-cloud backup mirror (дней). По умолчанию 7 = раз в неделю.",
    "default": 7,
    "minimum": 1,
    "maximum": 90
  },
  {
    "key": "backup.secondaryProvider",
    "type": "string",
    "description": "Cross-cloud backup: вторичный провайдер для периодического зеркала манифестов + _meta.json. Пусто — отключено. Должен быть авторизован и отличаться от primary.",
    "default": "",
    "enum": [
      "",
      "onedrive",
      "gdrive",
      "yandex",
      "dropbox"
    ]
  },
  {
    "key": "batchAddWarnThreshold",
    "type": "number",
    "description": "Порог количества файлов для предупреждения при пакетном добавлении",
    "default": 50,
    "minimum": 1
  },
  {
    "key": "canonicalHashAlgo",
    "type": "string",
    "description": "Канонический алгоритм хеширования манифеста. 'sha256' (по-умолчанию) сохраняет совместимость с v1. 'blake3' — быстрый pure-JS BLAKE3 (требует optional-зависимость @noble/hashes). 'dual' — пишет оба хеша во время migration-window, переключайтесь на 'blake3' когда все машины уже ≥ 7 дней работают в 'dual'. См. команду vscodesync.runHashAlgoMigrationCheck.",
    "default": "sha256",
    "enum": [
      "sha256",
      "blake3",
      "dual"
    ]
  },
  {
    "key": "codeLens.enabled",
    "type": "boolean",
    "description": "Показывать CodeLens с last-sync временем и кнопкой Pull над синхронизируемыми файлами",
    "default": true
  },
  {
    "key": "compressUploads",
    "type": "boolean",
    "description": "Gzip сжатие текстовых файлов на загрузке; blob в облаке с суффиксом `.gz`, флаг `_meta.files[].wireGzip`. Несовместимо с шифрованием workspace — при включённом encryption сжатие отключается.",
    "default": false
  },
  {
    "key": "conflictHotZoneCodeLens.enabled",
    "type": "boolean",
    "description": "Показывать CodeLens-«флейм» на строках, которые ≥ 1 раза участвовали в разрешённых конфликтах за 180 дней (данные из conflict heatmap).",
    "default": true
  },
  {
    "key": "diagnostics.profileSync",
    "type": "boolean",
    "description": "Включить сбор тайминга push/pull (hash ms / network ms / verify ms) для команды «VSCodeSync: Профиль синка». Минимальный оверхед, выкл по умолчанию.",
    "default": false
  },
  {
    "key": "digestIntervalMinutes",
    "type": "number",
    "description": "Интервал дайджеста уведомлений (мин)",
    "default": 30,
    "minimum": 5
  },
  {
    "key": "dropboxAppKey",
    "type": "string",
    "description": "App key Dropbox (OAuth). Оставьте пустым для использования встроенного. В консоли приложения добавьте redirect URI: http://127.0.0.1:8734/oauth-callback",
    "default": "lsuphteciqwcykn"
  },
  {
    "key": "encryption",
    "type": "boolean",
    "description": "Включить E2E-шифрование (AES-256-GCM) перед загрузкой на облако. Требует наличия ключа в SecretStorage. Первый Push после включения зашифрует данные; Pull на другой машине требует импорта того же ключа.",
    "default": false
  },
  {
    "key": "gdrive.folderCacheTtlSec",
    "type": "number",
    "description": "Время жизни кэша folder-id для Google Drive (секунды). Drive требует разрешать путь файла как серию `name=… and parent=…` запросов на каждый уровень иерархии — кэш позволяет пропускать эти GET'ы для уже виденных папок. 0 — отключить кэш.",
    "default": 600,
    "minimum": 0,
    "maximum": 86400
  },
  {
    "key": "gitBranchAutoSync",
    "type": "boolean",
    "description": "При смене git-ветки: Suspend для воркспейсов с другим gitBranch в манифесте; активация совпадающих, пересчёт их статусов и предложение накопившихся изменений уведомлением. Файлы двигаются только после вашего подтверждения. Требует расширение Git и настройку gitBranch.",
    "default": true
  },
  {
    "key": "googleDriveClientId",
    "type": "string",
    "description": "OAuth 2.0 Client ID (Desktop) для Google Drive (Google Cloud Console → APIs & Services → Credentials)",
    "default": ""
  },
  {
    "key": "hints.enabled",
    "type": "boolean",
    "description": "Показывать контекстуальные подсказки при возврате фокуса в окно (много конфликтов, переполненная квота, долгое отсутствие синхронизации). Однократно в 6 часов на каждый тип хинта.",
    "default": true
  },
  {
    "key": "historyLazyDrainMinutes",
    "type": "number",
    "description": "Период «отлива» очереди отложенных снимков истории при `historyMode = lazy` (мин).",
    "default": 10,
    "minimum": 1,
    "maximum": 720
  },
  {
    "key": "historyMode",
    "type": "string",
    "description": "Как сохранять снимки в `.history/` перед каждым push. `inline` — синхронно, +1 GET и +1 PUT на каждый push (историческое). `lazy` — складывать в очередь и отгружать пакетом раз в `historyLazyDrainMinutes` минут. `off` — не вести историю вовсе.",
    "default": "inline",
    "enum": [
      "inline",
      "lazy",
      "off"
    ],
    "enumDescriptions": [
      "Сохранять снапшот в .history/ сразу перед каждым push (по одному GET+PUT на push).",
      "Откладывать снапшоты в очередь, отгружать пакетом раз в N минут.",
      "Не вести историю. Самый быстрый режим, но без отката версий."
    ]
  },
  {
    "key": "historyVersions",
    "type": "number",
    "description": "Сколько версий каждого файла хранить в облачной `.history/`. 0 — отключить ротацию (старые версии накапливаются), 10 — историческое значение.",
    "default": 10,
    "minimum": 0,
    "maximum": 200
  },
  {
    "key": "hoverDiffPreview.enabled",
    "type": "boolean",
    "description": "Показывать hover поверх tracked-файлов с sync-статусом, возрастом последнего sync и ссылкой Pull / Resolve.",
    "default": true
  },
  {
    "key": "inlineConflictCodeLens.enabled",
    "type": "boolean",
    "description": "Показывать inline CodeLens над git-merge маркер-блоками (<<<<<<< / >>>>>>>): Keep mine | Take theirs | AI merge",
    "default": true
  },
  {
    "key": "localBackupDir",
    "type": "string",
    "description": "Папка для локальных бэкапов перед pull'ом (относительно корня workspace). Дефолт — `.vscode/vscodesync-local-backup`. Менять только если этот путь занят/нежелателен.",
    "default": ".vscode/vscodesync-local-backup"
  },
  {
    "key": "localBackupEnabled",
    "type": "boolean",
    "description": "Локальный бэкап перед перезаписью при pull",
    "default": true
  },
  {
    "key": "localBackupRetentionDays",
    "type": "number",
    "description": "Сколько дней хранить файлы в vscodesync-local-backup",
    "default": 7,
    "minimum": 0
  },
  {
    "key": "longAbsenceThresholdDays",
    "type": "number",
    "description": "Порог «долгого отсутствия» для подсказок (дней)",
    "default": 3,
    "minimum": 1
  },
  {
    "key": "massChangeGuard",
    "type": "boolean",
    "description": "Подтверждение перед push манифеста, который удалит много файлов (≥ 25 абсолютно или ≥ 50% от активных). Отключить — чтобы убрать модалку.",
    "default": true
  },
  {
    "key": "maxFileSizeMB",
    "type": "number",
    "description": "Максимальный размер одного файла для синхронизации (МБ). 0 — без лимита",
    "default": 5,
    "minimum": 0
  },
  {
    "key": "maxSnapshotsPerWorkspace",
    "type": "number",
    "description": "Максимум снапшотов на один workspace",
    "default": 20,
    "minimum": 1
  },
  {
    "key": "metaWriteRetries",
    "type": "number",
    "description": "Сколько раз пытаться записать `_meta.json` при `PRECONDITION_FAILED` (другая машина уже обновила meta) до сдачи.",
    "default": 3,
    "minimum": 1,
    "maximum": 10
  },
  {
    "key": "monthlyBandwidthLimitMB",
    "type": "number",
    "description": "Лимит трафика в месяц (МБ), 0 — без лимита",
    "default": 0,
    "minimum": 0
  },
  {
    "key": "notificationLevel",
    "type": "string",
    "description": "Уровень уведомлений VSCodeSync (minimal / normal / verbose)",
    "default": "normal",
    "enum": [
      "minimal",
      "normal",
      "verbose"
    ]
  },
  {
    "key": "notifications.emojiFree",
    "type": "boolean",
    "description": "Заменять эмодзи в уведомлениях на текстовые маркеры ([ok], [warn], [err]) — для корпоративных чатов и accessibility tools, которые перекодируют эмодзи.",
    "default": false
  },
  {
    "key": "onedrive.uploadChunkMB",
    "type": "number",
    "description": "Размер chunk'а в МБ при OneDrive upload session. Рекомендация Graph — кратно 320 КБ; по умолчанию 1.6 МБ. На быстром канале 4–8 МБ ускорит крупные файлы.",
    "default": 1.6,
    "minimum": 0.32,
    "maximum": 60
  },
  {
    "key": "onedrive.uploadSessionThresholdMB",
    "type": "number",
    "description": "Порог в МБ, выше которого OneDrive переходит на multipart upload session. Стандарт Graph — 4 МБ для простого PUT.",
    "default": 4,
    "minimum": 1,
    "maximum": 250
  },
  {
    "key": "onedriveClientId",
    "type": "string",
    "description": "Azure AD public client ID для входа OneDrive (device code)",
    "default": ""
  },
  {
    "key": "p2p.acceptIncomingFiles",
    "type": "boolean",
    "description": "Принимать файлы от P2P-пиров. Входящие ждут в .vscode/vscodesync-incoming, пока вы их не примените; при выключенной настройке сессия их игнорирует.",
    "default": false
  },
  {
    "key": "p2p.experimental",
    "type": "boolean",
    "description": "Enable experimental WebRTC P2P session (cloud-bypass mode). When off, the Start P2P Session command shows the planned wizard but does not open a DataChannel. Requires the optional @roamhq/wrtc binding to be loadable.",
    "default": false
  },
  {
    "key": "passkey.peerRegistrySync",
    "type": "string",
    "description": "Multi-device passkey registry sync (v2.20.4). When 'off' (default) — registry stays per-machine. 'p2p' fans out the local registry to peers over an authenticated P2P channel. 'cloud_mirror' publishes an encrypted blob to the active provider. Both transports require the recipient to opt-in too; the reconciler merges by credential id without losing local displayName / primaryId.",
    "default": "off",
    "enum": [
      "off",
      "p2p",
      "cloud_mirror"
    ]
  },
  {
    "key": "pauseBatteryThreshold",
    "type": "number",
    "description": "Процент батареи — ниже этого приостанавливать sync (0 — отключено)",
    "default": 15,
    "minimum": 0,
    "maximum": 100
  },
  {
    "key": "pauseOnMeteredConnection",
    "type": "boolean",
    "description": "Пауза sync на лимитированном соединении",
    "default": true
  },
  {
    "key": "presenceHeartbeatMinutes",
    "type": "number",
    "description": "Live presence heartbeat: периодически обновлять lastSeen в _machines.json. 0 — отключено. Рекомендуется 5 (~12 запросов/ч).",
    "default": 0,
    "minimum": 0,
    "maximum": 60
  },
  {
    "key": "providerHashVerify",
    "type": "boolean",
    "description": "После загрузки сравнивать дайджест файла, сообщённый провайдером (md5 у GDrive/Yandex, content_hash у Dropbox, sha256 у OneDrive), с локально вычисленным. При несовпадении — `INTEGRITY_FAILED`. Доп. round-trip к `getMetadata`. Пропускается для зашифрованных и gzip-сжатых загрузок.",
    "default": false
  },
  {
    "key": "pushOnCommit",
    "type": "boolean",
    "description": "После git-коммита пересчитать статусы затронутых воркспейсов. Отправка файлов — всегда ваше явное действие.",
    "default": false
  },
  {
    "key": "quickTransferTtlDays",
    "type": "number",
    "description": "Сколько дней разовая передача (Quick Transfer) хранится в облаке",
    "default": 7,
    "minimum": 1,
    "maximum": 365
  },
  {
    "key": "requireMachineApproval",
    "type": "boolean",
    "description": "Требовать одобрение новой машины в workspace",
    "default": false
  },
  {
    "key": "showFileDecorations",
    "type": "boolean",
    "description": "Показывать значки синхронизации на файлах в проводнике",
    "default": true
  },
  {
    "key": "showPreview",
    "type": "boolean",
    "description": "Показывать подтверждение перед добавлением файла в синхронизацию и перед Pull/Push/Sync workspace из панели Workspaces (план в Output + модальное окно)",
    "default": true
  },
  {
    "key": "smartConflictPrediction.broadcastCurrentEditing",
    "type": "string",
    "description": "Что публиковать в `_machines.json.currentEditing`. 'full' (по-умолчанию): полный относительный путь. 'anonymised': `sha256(relPath).slice(0,8)` — другие peers видят «машина X редактирует некий файл», но не путь. 'off': не публиковать — Smart Conflict Prediction теряет pre-save warnings, post-fact warning продолжит работать через soft-lock.",
    "default": "full",
    "enum": [
      "full",
      "anonymised",
      "off"
    ]
  },
  {
    "key": "smartConflictPrediction.enabled",
    "type": "boolean",
    "description": "Показывать status-bar warning, когда другая машина пометила активный файл как редактируемый (soft-lock pipeline).",
    "default": true
  },
  {
    "key": "smartSuggestions",
    "type": "boolean",
    "description": "Анализ activity.json: подсказка сгруппировать часто синхронизируемые файлы; ранний вопрос об архиве (~60 дн.) если workspaceInactiveDays > 60",
    "default": true
  },
  {
    "key": "snapshotRetentionDays",
    "type": "number",
    "description": "TTL снапшотов workspace в облаке (дней)",
    "default": 180,
    "minimum": 1
  },
  {
    "key": "snapshotSchedule",
    "type": "string",
    "description": "Расписание автоматических снапшотов. Пусто — отключено. Примеры: 'daily 03:00' или 'weekly mon 03:00'. Время локальное.",
    "default": ""
  },
  {
    "key": "softLock.enabled",
    "type": "boolean",
    "description": "Сообщать другим машинам «сейчас редактируется» для открытого файла (soft-lock в облачном манифесте). По умолчанию выключено: каждое объявление — скачивание и загрузка манифеста, что оправдано только при совместной работе.",
    "default": false
  },
  {
    "key": "softLockStaleHours",
    "type": "number",
    "description": "Через сколько часов «editingSince» в манифесте считается устаревшим soft-lock'ом и автоматически снимается (Health Check / repair).",
    "default": 3,
    "minimum": 1,
    "maximum": 168
  },
  {
    "key": "sync.concurrency",
    "type": "number",
    "description": "Сколько файлов синхронизировать **параллельно** внутри одного workspace. 1 = последовательно (старое поведение). Большие значения снижают сетевую задержку, но увеличивают пиковую нагрузку на канал и квоту провайдера.",
    "default": 4,
    "minimum": 1,
    "maximum": 32
  },
  {
    "key": "sync.workspaceConcurrency",
    "type": "number",
    "description": "Сколько workspace'ов синкать **параллельно** при `pushAll` / full sync. 1 = последовательно. Учитывайте rate-limit'ы провайдера: для Google Drive безопасно 1–2, для OneDrive 2–3.",
    "default": 2,
    "minimum": 1,
    "maximum": 16
  },
  {
    "key": "syncOnFocusDelayMs",
    "type": "number",
    "description": "Задержка перед пересчётом статусов при возврате фокуса в окно (мс).",
    "default": 3000,
    "minimum": 0
  },
  {
    "key": "syncOnOpen",
    "type": "boolean",
    "description": "При открытии отслеживаемого файла пересчитать статусы его воркспейса (тихий conditional GET). Скачивание — всегда ваше явное действие.",
    "default": true
  },
  {
    "key": "syncSummaryOnStartup",
    "type": "boolean",
    "description": "После запуска VS Code пересчитать статусы активных воркспейсов и показать сводку расхождений, если что-то отличается. Ничего не скачивается автоматически.",
    "default": true
  },
  {
    "key": "tasks.allowFileMutations",
    "type": "boolean",
    "description": "Разрешить задачам «vscodesync» отправлять, скачивать и создавать снапшоты. По умолчанию выключено: задача с `runOn: folderOpen` запускается сама, а VS Code не даёт расширению отличить такой запуск от запущенного вами.",
    "default": false
  },
  {
    "key": "telemetry",
    "type": "boolean",
    "description": "Разрешить телеметрию расширения (агрегаты: провайдер, число workspace, версия). Пути и имена файлов не отправляются. Учитывается также глобальная настройка телеметрии VS Code.",
    "default": false
  },
  {
    "key": "telemetryIngestUrl",
    "type": "string",
    "description": "Необязательный URL приёма событий (POST JSON). Пусто — только канал телеметрии VS Code, без внешнего сервера (Application Insights / Posthog и т.п.). Только http(s) без учётных данных в URL.",
    "default": ""
  },
  {
    "key": "templates.registryUrl",
    "type": "string",
    "description": "URL of the workspace template registry index (JSON: { templates: [{ manifestUrl }] }). Empty = use the default public index.",
    "default": ""
  },
  {
    "key": "tokenRefreshSkewMinutes",
    "type": "number",
    "description": "За сколько минут до истечения OAuth-токена начинать его обновлять. Применяется для всех провайдеров (Google Drive, OneDrive, Yandex.Disk, Dropbox).",
    "default": 5,
    "minimum": 1,
    "maximum": 60
  },
  {
    "key": "tombstonePurgeDays",
    "type": "number",
    "description": "Сколько дней метка удаления (tombstone) живёт в манифесте. Машина, пробывшая офлайн дольше, теряет отслеживание файлов, удалённых на другой машине.",
    "default": 30,
    "minimum": 1
  },
  {
    "key": "verifyRetries",
    "type": "number",
    "description": "Сколько раз перепроверять хэш blob'а после загрузки в режиме `verifyUploadHash = plaintext-only` до того, как признать рассинхрон.",
    "default": 3,
    "minimum": 1,
    "maximum": 10
  },
  {
    "key": "verifyUploadHash",
    "type": "string",
    "description": "Проверять ли результат загрузки blob'а перечитывая его обратно и сверяя хэш. `plaintext-only` (по умолчанию) — проверка делается только для незашифрованных файлов (как было). `never` — пропускать проверку всегда. Экономит 1 GET и трафик на каждый push; полагаемся на ETag провайдера.",
    "default": "plaintext-only",
    "enum": [
      "plaintext-only",
      "never"
    ],
    "enumDescriptions": [
      "Скачивать обратно blob после загрузки и сверять хэш — историческое поведение. Корректно, но добавляет 1 round-trip к каждому push.",
      "Не проверять. Самый быстрый режим — полагаемся на ETag и провайдер. Подойдёт для надёжных каналов и доверенных провайдеров."
    ]
  },
  {
    "key": "warnOnBinaryFiles",
    "type": "boolean",
    "description": "Предупреждать перед синхронизацией, если файл похож на двоичный",
    "default": true
  },
  {
    "key": "watchAdaptive",
    "type": "boolean",
    "description": "Адаптивный интервал watch mode",
    "default": true
  },
  {
    "key": "watchIntervalSeconds",
    "type": "number",
    "description": "Интервал опроса в watch mode (сек)",
    "default": 30,
    "minimum": 5
  },
  {
    "key": "watchMaxIntervalSeconds",
    "type": "number",
    "description": "Максимальный интервал backoff watch mode (сек)",
    "default": 300,
    "minimum": 30
  },
  {
    "key": "watchMode",
    "type": "boolean",
    "description": "Режим наблюдения: периодически пересчитывать статусы расхождений в фоне. Сам ничего не отправляет и не скачивает.",
    "default": false
  },
  {
    "key": "webhookDigestUrl",
    "type": "string",
    "description": "URL для webhook-дайджеста активности (Discord webhook, Slack webhook, Telegram bot `/sendMessage`, или generic JSON). Формат определяется по hostname URL. Команда — `VSCodeSync: Send Webhook Digest`.",
    "default": ""
  },
  {
    "key": "webhooks.enabled",
    "type": "boolean",
    "description": "Включить webhook уведомления",
    "default": false
  },
  {
    "key": "webhooks.fallbackAfterMinutes",
    "type": "number",
    "description": "Watch Mode: если за это время не было push-уведомлений от Graph, снова использовать interval polling и показать предупреждение. 0 — не переключаться на polling из-за тишины (только пока активна подписка).",
    "default": 5,
    "minimum": 0,
    "maximum": 10080
  },
  {
    "key": "webhooks.localPort",
    "type": "number",
    "description": "Локальный HTTP-порт (127.0.0.1) для приёма validation и уведомлений Graph. 0 — не слушать локально (внешний relay сам принимает POST).",
    "default": 0,
    "minimum": 0,
    "maximum": 65535
  },
  {
    "key": "webhooks.tunnelEnabled",
    "type": "boolean",
    "description": "Запустить встроенный smee.io туннель для webhooks при включённом режиме Watch + webhooks. Туннель даёт публичный URL для OneDrive/Google Drive без белого IP.",
    "default": false
  },
  {
    "key": "webhooks.url",
    "type": "string",
    "description": "Публичный HTTPS URL для Microsoft Graph (например ngrok → локальный порт). Должен совпадать с тем, что прокидывает туннель на webhooks.localPort.",
    "default": ""
  },
  {
    "key": "workspaceInactiveDays",
    "type": "number",
    "description": "Если давность синхронизации (max lastSync среди файлов workspace) превышает столько дней — при старте предложить архивировать (0 — отключить проверку)",
    "default": 90,
    "minimum": 0,
    "maximum": 3650
  },
  {
    "key": "yandex.apiTimeoutMs",
    "type": "number",
    "description": "Таймаут (мс) для API-запросов к Yandex.Disk (метаданные, auth).",
    "default": 30000,
    "minimum": 5000,
    "maximum": 300000
  },
  {
    "key": "yandex.dataTimeoutMs",
    "type": "number",
    "description": "Таймаут (мс) для upload PUT / download GET на Yandex.Disk. Для крупных файлов и медленного канала увеличьте.",
    "default": 120000,
    "minimum": 10000,
    "maximum": 600000
  },
  {
    "key": "yandex.lockedRetryDelayMs",
    "type": "number",
    "description": "Пауза (мс) перед повторной попыткой при HTTP 423 Locked от Yandex.Disk.",
    "default": 1500,
    "minimum": 100,
    "maximum": 30000
  },
  {
    "key": "yandexOAuthClientId",
    "type": "string",
    "description": "OAuth Client ID Яндекса. Оставьте пустым для использования встроенного. Redirect URI: http://127.0.0.1:8735/oauth-callback. Права зависят от vscodesync.yandexUseAppFolder.",
    "default": "6ee27a62c3ba4b05a69b682bef342570"
  },
  {
    "key": "yandexUseAppFolder",
    "type": "boolean",
    "description": "Использовать папку приложения Яндекс Диска (scope: cloud_api:disk.app_folder, путь app:/…). Файлы хранятся в «Приложения/{имя_приложения}/» и недоступны другим приложениям. При изменении этой настройки требуется повторная авторизация.",
    "default": false
  }
];

/** Every declared key, in the order the panel renders them. */
export const SETTINGS_KEYS: readonly string[] = SETTINGS_SCHEMA.map((s) => s.key);
